In [1]:
import numpy as np

### Numpy Arrays


In [8]:
a_list = [1,2,3,4]
a = np.array(a_list)

b = np.array([0.5, 1, 1.5, 2])

You can work with numpy arrays, similarly to python lists.

In [3]:
a[0],a[1]

(1, 2)

In [4]:
a[0:-1]

array([1, 2, 3])

A key difference between python lists and np array is that you can use **multi-indexing**

In [5]:
a[[0,2,1]]

array([1, 3, 2])

### Array Types

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

We can define the type explicitly when creating the array

In [10]:
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [12]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

You can use numpy to store other data types, however it is not recommended. The dtype is custom to numpy

In [14]:
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

### Dimensions and shapes
Can create multi dimension arrays

In [15]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [17]:
A.shape # How many rows and columns

(2, 3)

In [19]:
A.ndim # How many dimensions

2

In [20]:
A.size # Number of elements

6

##### Lets look at 3D array

In [21]:
B =  np.array([
    [
        [12,11,10],
        [ 9, 8, 7]
    ],
    [
        [5, 6, 4],
        [1, 2, 3]
    ]
])

In [22]:
B.dtype

dtype('int64')

In [23]:
B.shape

(2, 2, 3)

In [24]:
B.ndim

3

In [25]:
B.size

12

### Indexing and Slicing of Matrices

In [28]:
# Square matrix
A = np.array([
#    0, 1, 2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9]  #2
])

In [29]:
A[1] # 2nd row

array([4, 5, 6])

In [31]:
A[1][0] # 2nd row, 1st column

4

We can represent this using the multi-indexing feature of np

In [32]:
A[1, 0] # 2nd row, 1st column

4

The reason this syntax is better is because we can use slicing with it

In [37]:
A[0:2] # First row till second row

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
A[:2, 2:] # The last columns of the first two rows

array([[3],
       [6]])

You can modify values in an array

In [41]:
A[1] = np.array([10,10,10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

### Summary Statistics
Arrays have various methods that we can use to summarize statistics

In [42]:
a = np.array([1,2,3,4])

In [44]:
a.sum()

10

In [45]:
a.mean()

2.5

In [46]:
a.std() # Standard deviation

1.118033988749895

Or we can calculate these things per axis in the matrix

In [47]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [48]:
A.sum()

45

In [50]:
A.sum(axis=0) # Axis 0 will sum everything via columns. Vertical dimension

array([12, 15, 18])

In [51]:
A.sum(axis=1) # Axis 1 will sum everything across a row. Horizontal dimension

array([ 6, 15, 24])

### Broadcasting and Vectorized operations

In [52]:
a = np.array([0,1,2,3])

In [53]:
a + 10

array([10, 11, 12, 13])

In [54]:
a * 10

array([ 0, 10, 20, 30])

In [55]:
b = np.array([10, 10, 10, 10])

In [56]:
a + b

array([10, 11, 12, 13])